train:
  load_weights: False
  offline: False
env:
  env: ALE/SpaceInvaders-v5
  is_atari: True
model:
  use_inverse_dynamic: False
  channels_last: True
  encoder_config: [
    {
      model_name: 'cnn',
      in_keys: [ 'observation' ],
      out_keys: [ 'logits' ],
      model_config: {
        num_channels: [ 16, 32, 64 ],
        kernel_sizes: 3,
        activation_class: 'relu',
        squash_last_layer: True,
      },
    },
    {
      model_name: 'mlp',
      in_keys: [ 'logits' ],
      out_keys: [ 'logits' ],
      model_config: {
        out_features: 256,
        activation_class: 'relu',
        activate_last_layer: True,
      },
    },
  ]
algo:
  name: PPO
  training:
    lr: 3.0e-4
    train_batch_size: 4000
    sgd_minibatch_size: 128
    vf_loss_coeff: 0.01
stop:
  training_iteration: 10_000
  timesteps_total: 100_000
  episode_reward_mean: 1000.0

