device: null
#pretrained_model: ckpt/train/2024-08-20_04-34-49_Apf/t[01700]_r[316.39].pt
pretrained_model: null
ckpt_name: nstep=5
seed: 42

# collector
collector:
  total_frames: 4_000_000
  frames_per_batch: 20
  num_envs: 16
  eps_start: 1.0
  eps_end: 0.05
  annealing_frames: 2_000_000
#  init_random_frames: 10_000
  init_random_frames: 0

# buffer
buffer:
  buffer_size: 2_000_000
  batch_size: 256

# Optim
optim:
  lr: 3.0e-4
  max_grad_norm: null

# loss
loss:
  gamma: 0.99
  nstep: 7
  hard_update_freq: 1000
  utd_ratio: 1
  loss_type: l2
  use_value_rescale: True

# logger
logger:
  backend: wandb
  model_name: DQN
  exp_name: Train
  test_interval: 100_000
#  test_interval: 20_000
  test_steps: 2_000
  video: True
